// <auto-generated />
namespace S2021A5AS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_data_annotations_attributes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_data_annotations_attributes1));
        
        string IMigrationMetadata.Id
        {
            get { return "202107160434004_update_data_annotations_attributes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
