// <auto-generated />
namespace S2021A5AS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reload_entity_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reload_entity_data));
        
        string IMigrationMetadata.Id
        {
            get { return "202107160314039_reload_entity_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
