// <auto-generated />
namespace S2021A5AS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_user_string_associations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_user_string_associations));
        
        string IMigrationMetadata.Id
        {
            get { return "202107250142403_remove_user_string_associations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
