// <auto-generated />
namespace S2021A6AS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class album_summary_artist_bio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(album_summary_artist_bio));
        
        string IMigrationMetadata.Id
        {
            get { return "202107291849297_album_summary_artist_bio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
