// <auto-generated />
namespace S2021A6AS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class increasestrlenannotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(increasestrlenannotations));
        
        string IMigrationMetadata.Id
        {
            get { return "202107292251153_increase-strlen-annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
